### ISSUE TITLE
Does ConnectionPool::Wrapper need to be slower?

### ISSUE THREAD

**Issue by majkelcc** [mperham/connection_pool#105]
After reading part of the readme saying that `ConnectionPool::Wrapper` is `not high-performance` I started thinking whether it has to be that way.

Why for example not use a `Delegator`, or dynamically define methods in `method_missing`? I can run some benchmarks, maybe even prepare a PR, but first wanted to ask whether I'm not missing something obvious :)

**Comment by ch1c0t** [comment]
If performance improvement are not desirable in `ConnectionPool::Wrapper`, I'd love to have `ConnectionPool::FastWrapper`.

**Comment by mperham** [comment]
The whole point is Wrapper is a migration path. Being slower is incentive to migrate to a ConnectionPool. If you want a FastWrapper, you can certainly build it.

**Comment by majkelcc** [comment]
Hello @mperham, thank you for quick response. Performance aside, is there any other downside of using wrapper in my app?

**Comment by mperham** [comment]
The idea is that your method calls sometimes need to be grouped as a transaction.  For instance:

```ruby
redis.sadd(x, y)
redis.lpop(a, b)
```

If you use a wrapper, that's two individual checkouts and checkins, on possibly two different connections.  If you port to a connection pool, you optimize that connection usage:

```ruby
pool.with do |c|
  c.sadd(x, y)
  c.lpop(a. b)
end
```

And the code becomes more self-describing in demarcating a "transaction" or single operation. I don't know how better to describe it and it may not be really valuable to you but it is valuable to many pool users.
