### ISSUE TITLE
Consider to add max_idle_time for the connections

### ISSUE THREAD

**Issue by yifeireplay** [mperham/connection_pool#106]
We use this library to build connection pool for snowflake JDBC connections. The connections will by default be expired every 4 hours and you need to re-auth after the connection is expired.  So some inactive connections in the pool will become invalid after some time.

I think it is worthy to add max_idle_time in the config, we can actively/passively remove connections which has been idle beyond  the max_idle_time. What do you think?

**Comment by mperham** [comment]
Connections should be self-repairing.

**Comment by yifeireplay** [comment]
Fair enough since it is also mentioned in the README.

Do you think letting the pool shrink in non-peak time is a good idea?

**Comment by mperham** [comment]
I think implementing pool shrink would be a reasonable, useful feature to have.  Happy to review a PR in that direction.
