### ISSUE TITLE
Performance difference between using ConnectionPool & ConnectionPool::Wrapper

### ISSUE THREAD

**Issue by ysv** [mperham/connection_pool#120]
@mperham You have mentioned [here](https://github.com/mperham/connection_pool/blob/master/lib/connection_pool.rb#L8) that there is difference in execution speed if we pass block to #with vs using Wrapper

Could you clarify please what is the speed degradation in numbers ?

As far as I understood it's caused because in case of using Wrapper:
1. ruby is trying to find method with proper name
2. ruby execute #method_missing
3. #method_missing execute #with

But if we use #with ruby will execute this method directly.
Am I right ?

**Comment by mperham** [comment]
I’m not here to do work for you. You are welcome to write a benchmark and send a PR with a write up for the readme. 👍🏻
