### ISSUE TITLE
As of v2.2.3 it breaks with ruby < 2.0.0

### ISSUE THREAD

**Issue by amuta** [mperham/connection_pool#133]
Within the `v.2.2.3` release, the removal of the line `if Thread.respond_to?(:handle_interrupt)` from `lib/connection_pool.rb` will cause the `NoMethodError` for ruby versions before `2.0.0`.

The commit that caused this behavior 5f72d5372f88b5ac696904009b01afe70feede64 at line 57

It breaks because the `handle_interrupt` was added (renamed from another method actually) to the `Thread` class only in the `2.0.0` release, see [it here](https://github.com/ruby/ruby/commit/0f9b33c793f225c1b817d73e5c915050c429edc4)

> * thread.c: rename methods:
>from Thread.async_interrupt_timing to Thread.handle_interrupt,

I think the main problem is that the `gemspec` does not say anything about not supporting projects with older ruby versions which would prevent the gem to update from such projects.

**Comment by mperham** [comment]
So send a PR to fix it?

**Comment by mayrsascha** [comment]
@mperham I guess it would be a good idea then to specify the required ruby version for this gem? There is 
a [`required_ruby_version` configuration option for the Gemspec](https://guides.rubygems.org/specification-reference/#required_ruby_version), that will give people trying to install it with a lower Ruby version an error when they try to install it. If you agree with me let me know and I'll open a PR.

**Comment by mperham** [comment]
Great idea.
