### ISSUE TITLE
What does "connections should be self-repairing" mean?

### ISSUE THREAD

**Issue by epetre** [mperham/connection_pool#155]
In the [readme](https://github.com/mperham/connection_pool/blob/master/README.md) it says that we have to ensure "connections should be self-repairing". I would like to make sure I'm respecting this requirement, but I am not sure what it means.

Sorry for the probably noob question here.
But I can't find the answer to this even after looking around.

We are getting sporadic `Redis::CannotConnectError: Error connecting to Redis
` errors and we were thinking that maybe we are trying to access dead connections or we are not configured properly to maintain them.

What does "connections should be self-repairing" mean?
- Does it mean that I have to check the connection status in every `with` block?
- Does it mean that I have to ensure the Redis server or client must be configured in some specific way?

**Comment by epetre** [comment]
Any idea?

**Comment by mperham** [comment]
It means the pool will never discard a connection object. If a problem develops with the object, the object must have logic internally to try to fix the issue.  For instance your Redis client should be trying to connect on every operation. The Redis client is self-repairing.

**Comment by epetre** [comment]
Thank you for clarifying!
