### ISSUE TITLE
Remove dependnecy on RubyGems

### ISSUE THREAD

**Issue by voxik** [mperham/connection_pool#158]
The PR #157 introduces unnecessary dependency on RubyGems and therefore I am facing issues trying to build Ruby on Fedora running this snippet:

~~~
$ make runruby 'TESTRUN_SCRIPT=-e "   module Bundler; module Persistent; module Net; module HTTP;   end; end; end; end;   require '\''bundler/vendor/net-http-persistent/lib/net/http/persistent'\'';   puts Bundler::Persistent::Net::HTTP::Persistent::VERSION"'
./revision.h unchanged
RUBY_ON_BUG='gdb -x ./.gdbinit -p' ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems  -e "   module Bundler; module Persistent; module Net; module HTTP;   end; end; end; end;   require 'bundler/vendor/net-http-persistent/lib/net/http/persistent';   puts Bundler::Persistent::Net::HTTP::Persistent::VERSION" 
/builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/connection_pool/lib/connection_pool/wrapper.rb:35:in `<class:Wrapper>': uninitialized constant Gem (NameError)
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/connection_pool/lib/connection_pool/wrapper.rb:2:in `<class:ConnectionPool>'
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/connection_pool/lib/connection_pool/wrapper.rb:1:in `<top (required)>'
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/connection_pool/lib/connection_pool.rb:126:in `require_relative'
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/connection_pool/lib/connection_pool.rb:126:in `<top (required)>'
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:4:in `require_relative'
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:4:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
make: *** [uncommon.mk:1248: runruby] Error 1
~~~

I don't think that the code or library should depend on RubyGems, therefore I propose to revert the change.

Please note that this was initially reported as rubygems/rubygems/issues/5119

**Comment by deivid-rodriguez** [comment]
I'm obviously against since I'm the one who proposed the patch 😅. But either way it doesn't seem like a big deal.

**Comment by mperham** [comment]
I don't understand the usecase. Rubygems is baked into Ruby. Why are you running connection_pool during a ruby build suite?

**Comment by mperham** [comment]
> Since connection_pool is bundled in Ruby

But connection_pool is not bundled with Ruby. And how could a connection_pool library have a security issue? I'm very confused.

**Comment by mperham** [comment]
@deivid-rodriguez I'm in favor of reverting. I don't think old `preview` support is worth the implicit dependency.

**Comment by deivid-rodriguez** [comment]
Sure, no big deal.

**Comment by voxik** [comment]
> > Since connection_pool is bundled in Ruby
> 
> But connection_pool is not bundled with Ruby.

It is bundled via RubyGems/Bundler:

https://github.com/ruby/ruby/tree/master/lib/bundler/vendor/connection_pool/lib

> And how could a connection_pool library have a security issue? I'm very confused.

Well, I honestly don't know if and how connection_pool could be vulnerable. But it is bundled and in Fedora/RHEL, we cannot treat it differently.

**Comment by nurse** [comment]
As far as I understand, `make runruby` is for CRuby development feature. Requesting support it to gems sounds not reasonable. If you request such non reasonable requests to gems, we'll remove `--disable-gems` feature.

**Comment by deivid-rodriguez** [comment]
@mperham Does https://github.com/rubygems/rubygems/pull/5136 change your mind at all?

**Comment by mperham** [comment]
It seems like a lot of work to support an old preview that no one is using anymore. I don't see the need.
