### ISSUE TITLE
Observability for wait time, low water mark etc?

### ISSUE THREAD

**Issue by pda** [mperham/connection_pool#161]
At Buildkite we would love to track a ConnectionPool's min/max/avg/p99 wait time, and perhaps its low water mark of available connections. However I believe these things would require ConnectionPool to track additional thread-synchronized state, and have some awareness of the desired aggregations (min/max/avg/p99 etc).

The wait time figures would be fantastic for capacity planning / tuning / monitoring, to be sure a connection pool isn't an inadvertent bottleneck. Some of the aggregations would be tricky to implement without maintaining lots of data in memory.

Re. low water mark, the methods added in #97 make it easy to sample the current utilization at a point in time, but there's no way to see how low the available connection count gets between samples.

These stats would be valuable, but I suspect the complexity and perhaps performance implications might outweigh their benefits.

The caller could perhaps track this externally, but that's tricky if the ConnectionPool is being passed to another library (e.g. Sidekiq!). I suppose they could also be implemented as a ConnectionPoolMetrics wrapper around ConnectionPool, if keeping that complexity out of ConnectionPool is desirable.

Anyway — since there's design/complexity/performance trade-offs involved, I figured I'd float the idea prior to going too deep on implementation. I suspect it might be a non-starter. Any thoughts or prior art? Thanks!

**Comment by mperham** [comment]
For the time being, I consider c_p finished and don't wish to make any changes beyond simple refactoring to make observability easier. If you need a change to make your c_p hooks safer/easier, I'd be happy to see a PR.

**Comment by pda** [comment]
No worries, thanks 👍🏼
