### ISSUE TITLE
Automatic fork detection

### ISSUE THREAD

**Issue by casperisfine** [mperham/connection_pool#165]
### Context

When using connection pools in conjunction with forking servers, a common need is to close all connections before or after fork to avoid sharing them with other processes. 

There is two school of thoughts or approaches on this:

  -  Some believe that libraries shouldn't deal with this at all, and just expose some kind of `at_fork` method to be called by the application (e.g. [Sequel](https://github.com/jeremyevans/sequel/blob/2392145025c60d3c127bc1b921130598409f249c/doc/fork_safety.rdoc#fork-safety-)).
  - Others think that the above is often a bit unwieldy, and prone to error, and prefer to automatically detect when a fork happened, and when it does drop all connections (e.g. [Active Record](https://github.com/rails/rails/blob/32ea85f1c232261214ccc155f75349654fb7ed74/activerecord/lib/active_record/connection_adapters/pool_config.rb#L73),  [`redis-rb`](https://github.com/redis-rb/redis-client/commit/bec4931c952b6196c76977356238dbaf4f2e1293).

### Problem

While exposing an `at_fork` callback and requiring the final user to call it whenever they fork is conceptually the cleaner thing to do, it isn't always easy to implement. Connection pools are often store privately inside some objects, so you need to expose them as public methods on a class or module which forces you with some global state etc. See for instance this `net-http-persistent` PR: https://github.com/drbrain/net-http-persistent/pull/140

So I think `connection_pool`, being very popular, could help here by doing automatic closing of connection when a fork is detected, either by default or as an option.

e.g.

```ruby
pool = ConnectionPool.new(auto_reload_after_fork: true) { ... }
```

### Considerations

For simpler protocols, simply closing the TCP socket after fork is fine. However in some more complex protocols, the client send some kind of `CLOSE` message to the server before closing the socket, which may cause the original connection in the parent process to also be closed.

In the vast majority of cases it's fine, because generally a process that forks no longer use its connection pools (e.g. `unicorn master`). But in rare cases it can be undesirable. ~~This may either preclude enabling this as a default, or would need explicit documentation.~~ However having the parent connection being asynchronously closed is overall a much safer error state than to share it with the parent. So I think even in such case it would be a positive.

cc @mperham

**Comment by mperham** [comment]
I like the existing self-repairing connections which save their creation PID and verify on reuse  as with redis-rb but that is a lot of unnecessary checks 99% of the time. I heard something about a `Process._fork_` decorator? It would be great if Ruby allowed us to register interest in a fork event.

**Comment by mperham** [comment]
I guess my question is why that fork tracker isn't built into stdlib? Was there any discussion about a broader feature within Ruby itself? Hanami and other frameworks like Sidekiq could also use this fork tracking.

I do not like config knobs so I would suggest it's always on unless there's a good usecase otherwise. Possibly Ruby 3.1+ only?

**Comment by casperisfine** [comment]
> I guess my question is why that fork tracker isn't built into stdlib?

You can read the full discussion here: https://bugs.ruby-lang.org/issues/17795, but the TL;DR; is that some people feared such API could be misused. `Process._fork` was the compromise I proposed to make it easier to implement in libraries.

> I do not like config knobs so I would suggest it's always on unless there's a good usecase otherwise.

Your library, your call.

> Possibly Ruby 3.1+ only?

As in solely use a `Process._fork` decorator? No objections, but that means tracking all the instances in a `ObjectSpace::WeakMap` or using `ObjectSpace.each_object` to find all the instances. Just so you know.

I can open a PR tomorrow.

**Comment by mperham** [comment]
I think 3.1+ and using `each_object` will give us a clean, simple impl. Finalizer-style references are easy to get wrong and cause a leak.

**Comment by eregon** [comment]
This seems a nice feature. Accidental connection sharing is a pretty bad bug.

In general `ObjectSpace::WeakMap` seems better than `each_object`, because `each_object` is `O(objects in heap)` (and is not handled on JRuby). But since fork is only implemented on CRuby, it'd be great if this has no cost on JRuby/TruffleRuby which don't need this feature.

**Comment by casperisfine** [comment]
PR is here: https://github.com/mperham/connection_pool/pull/166

@eregon feel free to review the Jruby Truffle compat (especially for the optional `ObjectSpace::WeakMap` part).
