### ISSUE TITLE
Connections exceeding size of connection pool occasionally.

### ISSUE THREAD

**Issue by skunkworker** [mperham/connection_pool#170]
We are currently using `protobuf-nats` gem in order to have a talk over nats rpc and utilize `connection_pool` in order to limit the number of connections. See https://github.com/abrandoned/protobuf-nats/blob/master/lib/protobuf/nats/client.rb#L18

Across our hundreds of servers we have noticed some that have the number of true connections (as reported from our nats servers, which can track subscriptions). In some cases the service has 1000 true connections but was only passed 512 in the pool initializer. 

But the most frustrating aspect is that this only happens occasionally and only a few instances. 

@film42

**Comment by film42** [comment]
I'm inclined to say this is a protobuf-nats issue. I referenced a new issue to investigate. I think we should close this for now.

**Comment by skunkworker** [comment]
Closing to focus in `protobuf-nats`
