### ISSUE TITLE
2.4.1 Memory leak?

### ISSUE THREAD

**Issue by jeremiemv** [mperham/connection_pool#179]
Hi Mike 👋 

We started having _Error R14 (Memory quota exceeded)_ on Heroku  after we released to staging this morning.
The release was only a patch release of `Sidekiq` but the memory usage is only going up for the Web processes.
So I was suspecting `connection_pool`'s code change.

But it looks like the new code introduced an option the `auto_reload_after_fork` which doesn't change the default behavior.
https://github.com/mperham/connection_pool/pull/177/files

We had very little to no traffic.

Happy to help troubleshoot.

<img width="1518" alt="Screenshot 2023-05-25 at 4 20 52 PM" src="https://github.com/mperham/connection_pool/assets/232621/0706231b-6674-4436-93b1-fb28430d9b96">
<img width="1227" alt="Screenshot 2023-05-25 at 4 17 29 PM" src="https://github.com/mperham/connection_pool/assets/232621/f733dafb-e994-40f3-984a-e8f03554d583">

**Comment by mperham** [comment]
Hmmm, yeah I agree there's not much in Sidekiq 7.1.1 that seems suspicious.

Do you do any forking in your app code? You're the first person to report any issues so far. Can you revert them one at a time and see which reverts the behavior?

**Comment by jeremiemv** [comment]
After I restarted the dynos, the memory consumption is back to normal. No explanation :/ 

Going to close the issue.
