### ISSUE TITLE
Permanently lost connections

### ISSUE THREAD

**Issue by zanker** [mperham/connection_pool#71]
I believe this is an issue but don't quite have a test case to confirm it right now.

Anytime we remove a connection from the thread stack and transition it into the global stack (or discard it), if execution is interrupted we will permanently lose the connection but the global stack still counts it as if it exists.

We can fix this in MRI by using `handle_interrupt` (which is what @tamird did originally).

In JRuby, that's not available. I don't think there's a good solution to that, besides either rewriting connection_pool to follow the same model that ActiveRecord does, where we never pop a connection off the stack and instead flag as in use and then have a reaper that culls them after a set period of inactivity.

Maybe on JRuby you could add a rescue for Timeout::Error in the ensure. That at least covers the common case, but if you have nested timeouts and they all fire you still have the problem.

**Comment by tamird** [comment]
I believe this is moot, now that #75 is merged.
