### ISSUE TITLE
v2.2.0 tag missing?

### ISSUE THREAD

**Issue by matthewrudy** [mperham/connection_pool#77]
Hi.

Today I was trying to debug an error in our app with connection handling.
And in trying to diff all the changed dependencies I noticed that there is no `v2.2.0` tag pushed to github.

I'm not sure if that's intentional, or accidental.

Looking at the commit history, I guess that the 2.2.0 version of the gem is at https://github.com/mperham/connection_pool/commit/6007d32b625634f02f6fb7d12d625490f76ceba8

But, nevertheless, a git tag would be helpful.

Thanks.

**Comment by mperham** [comment]
Well poop, I must have used gem build/push rather than rake release.  Sorry bout that.  Done and thanks for the legwork to determine the commit.

**Comment by matthewrudy** [comment]
Great.
Thanks @mperham.
