### ISSUE TITLE
Can I "warm" a ConnectionPool?

### ISSUE THREAD

**Issue by rmosolgo** [mperham/connection_pool#85]
Hi, thanks for the great gem! We use it in [`react-rails` for server rendering](https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering.rb#L12). 

Let's say my pool is: 

```ruby 
ConnectionPool.new { really_long_setup }
```

And later I'm going to need 10 of those. Is there a way I can do the `really_long_setup` ahead of time? 

I thought maybe 

```ruby 
pool_size.times do 
  pool.with { |member| member }
end
```

but I would _expect_ that to use the same member each time. (Also, I'm not sure how I could _tell_ if the pool was initialized or not.)

**Comment by mperham** [comment]
You can perform some work or instantiate the first resource in a Rails initializer but there's no easy way to make a connection pool eager load its resources.  Do you mean that all 10 elements require a long setup to create?  If so, I'm not sure there's any easy solution to your problem.

**Comment by rmosolgo** [comment]
Fair 'nuf, I think one _would_ be enough. (Basically, for production, I'd rather raise errors at startup instead of randomly at runtime whenever the pool gets hit.)

Thanks!
