### ISSUE TITLE
Instrumenting checkout and query times?

### ISSUE THREAD

**Issue by jeffblake** [mperham/connection_pool#86]
I'm trying to set up a scheduler that measures the average time it takes to checkout a connection from the pool, and the query time spent while using it, and logging that to `$stdout` in a format Librato can understand. Can this be done? Or even better, `ActiveSupport::Notification` support, or some sort of generic `LogSubscriber`.

**Comment by guyisra** [comment]
Instrumenting the connection pool usage would also be nice, so we can check if the connection pool is too big or too small

**Comment by atomical** [comment]
Do either of you guys have an example of checking connection health?

**Comment by mmontagna** [comment]
@atomical I've forked the gem and added the ability to add an arbitrary connection health check here https://github.com/mmontagna/healthy_pools

**Comment by florrain** [comment]
Also interested in instrumenting the GEM, anybody have pointers?

**Comment by atomical** [comment]
@florrain I wrote a [wrapper](https://github.com/atomical/tiny_tds_wrapper) for TinyTDS that disconnects and reconnects when exceptions are raised. It can be used with connection pooling gems.
