### ISSUE TITLE
Provide a list of different connections

### ISSUE THREAD

**Issue by archan937** [mperham/connection_pool#90]
Hi,

Is it possible to provide a list of hosts to which the pool will connect to randomly? (unless the connection is dead of course)

Some pseudo code:

```
Pond.wrap(:hosts => ["localhost:1234", "localhost:1235", "localhost:1236"]) {|host| Redis.new host}
```

Thanks.

**Comment by mperham** [comment]
That's not my API, not sure what you're talking about.

**Comment by archan937** [comment]
Yeah, sorry for the copy-pasting. I also asked a similar question to the writer of Pond, sorry.

I actually want to connect to a sharded cluster but unfortunately I don't have a lot of experience on that area. I was wondering whether or not connection_pool could provide a part of the solution.

Please excuse me for the clumsy comments. I am kinda lost in the dark.

**Comment by mperham** [comment]
That's not something ConnectionPool could ever provide.  ConnectionPool provides a pool of resources and a way to reserve one for exclusive use.  It doesn't know about hosts, ports or anything aside from a set of shared Objects.

**Comment by archan937** [comment]
Ok. Well, thanks anyway for the quick response, Mike. Thanks for all the good work you have done for the Ruby community. Cheers.
