### ISSUE TITLE
Documentation on checkin, checkout, and shutdown

### ISSUE THREAD

**Issue by krainboltgreene** [mperham/connection_pool#98]
I can contribute this myself if I get direction.

**Comment by mperham** [comment]
What questions did you have?  The README is the docs.  Can you add your content there and send a PR?

**Comment by mperham** [comment]
Keep in mind, I don't want people using checkout/checkin so I don't publicize them.  They should be using `with` when possible.

**Comment by krainboltgreene** [comment]
Ah, I see.
